# Generated by Django 4.0.5 on 2022-08-23 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionInformationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_user_title', models.CharField(max_length=100)),
                ('solution_user_description', models.CharField(max_length=100)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='ENTRY', max_length=13)),
                ('awards', models.CharField(blank=True, max_length=300, null=True)),
                ('employment_history', models.TextField(blank=True, null=True)),
                ('lab_software', models.TextField(blank=True, null=True)),
                ('lab_hardware', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
