# Generated by Django 4.0.5 on 2022-08-23 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Oil & Gas', 'Oil & Gas'), ('Electricity', 'Electricity'), ('Agriculture', 'Agriculture'), ('Information Technology', 'Information Technology'), ('Finance', 'Finance')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_title', models.CharField(max_length=100)),
                ('challenge_description', models.CharField(blank=True, max_length=450)),
                ('challenge_location', models.CharField(default='Canada', max_length=50)),
                ('skills', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessinformation')),
                ('industry', models.ManyToManyField(related_name='industry', to='challenge_creator.industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Statement',
                'verbose_name_plural': 'Challenge Statement',
            },
        ),
    ]
