# Generated by Django 4.0.5 on 2022-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0002_alter_challengestatement_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestatement',
            name='skills',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
